# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = []
description = ""
language = "javascript"
manifest_version = 3
name = "Example Fastly MCP Server (TypeScript)"
service_id = "JX3p6ti1efkf2rgF9wqVz4"

[local_server]

[scripts]
  build = "js-compute-runtime ./dist/index.js"
