# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = []
description = ""
language = "javascript"
manifest_version = 3
name = "Example Fastly MCP Server (JavaScript)"
service_id = "TewdS3G891B3hIc1Yq7xL8"

[local_server]
