project_id = "example-supabase-js"

[auth]
enabled = false

[api]
enabled = false

[studio]
enabled = false

[realtime]
enabled = false

[storage]
enabled = false

[inbucket]
enabled = false

[analytics]
enabled = false

[functions.mcp-server]
verify_jwt = false
entrypoint = "./functions/mcp-server/index.js"
