name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    if: github.ref == 'refs/heads/main' && github.actor == 'phuctm97' && github.triggering_actor == 'phuctm97'
    name: ${{ github.workflow }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: fregante/setup-git-user@v2
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - run: pnpm install
      - run: pnpm exec nx run-many -t typecheck lint build
      - run: pnpm exec nx release --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
